export let COURSE = [
    {
      CourseId: '35',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary1',
      CourseDetailedDescription: 'This is UtkarshLibrary1',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '10',
      StandardPrice: '13.00',
      MemberPrice: '12.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '1',
      NoDiscount: '0',
      IncludeIn30DayTrial: '0',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '1',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-30T18:50:49',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-30T18:50:49',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Physical',
    },
    {
      CourseId: '44',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary10',
      CourseDetailedDescription: 'This is UtkarshLibrary10',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '9',
      StandardPrice: '0.00',
      MemberPrice: '0.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '0',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-30T13:06:29',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-30T13:06:29',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Online',
    },
    {
      CourseId: '45',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary11',
      CourseDetailedDescription: 'This is UtkarshLibrary11',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '10',
      StandardPrice: '0.00',
      MemberPrice: '0.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '1',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-27T11:32:29',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-27T11:32:29',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Physical',
    },
    {
      CourseId: '48',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary12',
      CourseDetailedDescription: 'This is UtkarshLibrary12',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '9',
      StandardPrice: '0.00',
      MemberPrice: '0.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '1',
      CreatedBy: '1',
      CreatedDateTime: '2021-08-02T09:56:19',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-08-02T09:56:19',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Online',
    },
    {
      CourseId: '36',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary2',
      CourseDetailedDescription: 'This is UtkarshLibrary2',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '9',
      StandardPrice: '10.00',
      MemberPrice: '10.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '1',
      NoDiscount: '0',
      IncludeIn30DayTrial: '0',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '1',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-27T11:32:40',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-27T11:32:40',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Online',
    },
    {
      CourseId: '37',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary3',
      CourseDetailedDescription: 'This is UtkarshLibrary3',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '10',
      StandardPrice: '10.00',
      MemberPrice: '10.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '0',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-27T11:32:54',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-27T11:32:54',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Physical',
    },
    {
      CourseId: '38',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary4',
      CourseDetailedDescription: 'This is UtkarshLibrary4',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '9',
      StandardPrice: '0.00',
      MemberPrice: '0.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '1',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-27T11:33:05',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-27T11:33:05',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Online',
    },
    {
      CourseId: '39',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary5',
      CourseDetailedDescription: 'This is UtkarshLibrary5',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '9',
      StandardPrice: '0.00',
      MemberPrice: '0.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '0',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-27T11:33:47',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-27T11:33:47',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Online',
    },
    {
      CourseId: '40',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary6',
      CourseDetailedDescription: 'This is UtkarshLibrary6',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '10',
      StandardPrice: '10.00',
      MemberPrice: '10.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '1',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-27T11:33:58',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-27T11:33:58',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Physical',
    },
    {
      CourseId: '41',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary7',
      CourseDetailedDescription: 'This is UtkarshLibrary7',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '9',
      StandardPrice: '9.00',
      MemberPrice: '9.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '0',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-27T11:34:45',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-27T11:34:45',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Online',
    },
    {
      CourseId: '42',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary8',
      CourseDetailedDescription: 'This is UtkarshLibrary8',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '10',
      StandardPrice: '8.00',
      MemberPrice: '8.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '1',
      CreatedBy: '1',
      CreatedDateTime: '2021-08-02T09:56:56',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-08-02T09:56:56',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Physical',
    },
    {
      CourseId: '43',
      CompanyId: '1',
      CourseName: 'UtkarshLibrary9',
      CourseDetailedDescription: 'This is UtkarshLibrary9',
      CourseTypeId: '4',
      TargetAudiance: null,
      ServiceCategory: null,
      OtherCourseTypeId: '9',
      StandardPrice: '8.00',
      MemberPrice: '8.00',
      OtherPrice: '0.00',
      MaxAllowed: null,
      IsAvailableForFree: '0',
      ApplyMemberDiscount: '0',
      MarkItAsHotTopic: '0',
      SetOtherDiscountOtherDiscount: '0',
      NoDiscount: '1',
      IncludeIn30DayTrial: '1',
      ImageFilePath: null,
      UploadContentPath: null,
      StartDate: null,
      StartTime: null,
      EndDate: null,
      EndTime: null,
      MeetingLink: null,
      ModeratorName: null,
      Password: null,
      Address1: null,
      Address2: null,
      StateId: null,
      City: null,
      IsActive: '1',
      CreatedBy: '1',
      CreatedDateTime: '2021-07-27T11:35:06',
      LastEditedBy: '1',
      LastEditedDateTime: '2021-07-27T11:35:06',
      CourseTypeName: 'Online Library',
      HasVenu: '0',
      Duration: '0',
      ServiceCategoryNames: null,
      TargetAudianceNames: null,
      OtherCourseTypeName: 'Offline',
    },
  ],
  onlineArray = COURSE.filter(item =>
    item.OtherCourseTypeName.includes('Online'),
  ),
  physicalArray = COURSE.filter(item =>
    item.OtherCourseTypeName.includes('Physical'),
  );
